#!/bin/sh

CHECK=`grep "^listen[[:space:]]*=[[:space:]]*.*:9000$" /etc/opt/rh/rh-php56/php-fpm.d/www.conf`
if [ -n "$CHECK" ]; then
    logger -p local6.notice -t installer "app-php-engines-core - updating listen port for PHP 5.6"
    sed -i -e 's/^listen[[:space:]]*=.*/listen = 127.0.0.1:9056/' /etc/opt/rh/rh-php56/php-fpm.d/www.conf
fi

CHECK=`grep "^listen[[:space:]]*=[[:space:]]*.*:9000$" /etc/opt/rh/rh-php70/php-fpm.d/www.conf`
if [ -n "$CHECK" ]; then
    logger -p local6.notice -t installer "app-php-engines-core - updating listen port for PHP 7.0"
    sed -i -e 's/^listen[[:space:]]*=.*/listen = 127.0.0.1:9070/' /etc/opt/rh/rh-php70/php-fpm.d/www.conf
fi

CHECK=`grep "^listen[[:space:]]*=[[:space:]]*.*:9000$" /etc/opt/rh/rh-php71/php-fpm.d/www.conf`
if [ -n "$CHECK" ]; then
    logger -p local6.notice -t installer "app-php-engines-core - updating listen port for PHP 7.1"
    sed -i -e 's/^listen[[:space:]]*=.*/listen = 127.0.0.1:9071/' /etc/opt/rh/rh-php71/php-fpm.d/www.conf
fi
